-   id: kustomize-check
    name: kustomize docker image
    description: Kustomize Check from Docker Image
    entry: gazby/kustomize-check:dev
    language: docker_image
    args: [overlay/production-us]
    always_run: false
    pass_filenames: false
    files: ((^|/)*.(ya?ml)$)
-   id: kustomize-check-local
    name: kustomize docker local
    description: Kustomize Check via Local Docker Build
    entry: kustomize build
    language: docker
    args: [overlay/production-us]
    always_run: false
    pass_filenames: false
    files: ((^|/)*.(ya?ml)$)
-   id: kustomize-check-system
    name: Kustomize Check using installed kustomize binary
    entry: kustomize build
    language: system
    args: [overlay/production-us]
    always_run: false
    pass_filenames: false
    files: ((^|/)*.(ya?ml)$)
-   id: kustomize-check-kubeconform
    name: kustomize docker image with kubeconform
    description: kustomize
    entry: gazby/kustomize-check:dev --with-kubeconform
    language: docker_image
    args: [overlay/production-us]
    always_run: true
    pass_filenames: false
