-   id: kustomize
    name: kustomize docker image
    description: Kustomize Check from Docker Image
    entry: gazby/kustomize-check:dev
    language: docker_image
    args: [overlay/production-us]
    always_run: false
    pass_filenames: false
    files: ((^|/)*.(ya?ml)$)
-   id: kustomize-local
    name: kustomize docker local
    description: Kustomize Check via Local Docker Build
    entry: /app/run.sh
    language: docker
    args: [overlay/production-us]
    always_run: false
    pass_filenames: false
    files: ((^|/)*.(ya?ml)$)
-   id: kustomize-kubeconform
    name: kustomize docker image with kubeconform
    description: kustomize
    entry: gazby/kustomize-check:dev --with-kubeconform
    language: docker_image
    args: [overlay/production-us]
    always_run: true
    pass_filenames: false
-   id: kustomize-kubeconform-local
    name: Kustomize and kubeconform checks via local docker build
    description: kustomize and kubeconform local
    entry: /app/run.sh --with-kubeconform
    language: docker
    args: [overlay/production-us]
    always_run: true
    pass_filenames: false
