---
name: "build and push image"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  KUSTOMIZE_VERSION: v5.2.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: |
            gazby/kustomize-check
          tags: |
            type=edge,branch=main
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to docker registry
        id: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  tag_release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Create Tag
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            const { KUSTOMIZE_VERSION } = process.env
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${KUSTOMIZE_VERSION}`,
              sha: context.sha
            })

      - name: Update Tag
        uses: actions/github-script@v6
        with:
          script: |
            const { KUSTOMIZE_VERSION } = process.env
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `tags/${KUSTOMIZE_VERSION}`,
              sha: context.sha
            })
